### PR TITLE
update serving_conf.yaml

### PR DESCRIPTION
**Pull request by asdfsx**
Update serving_conf.yaml

If the servingIP, servingPort is empty, old template will create config like below
```
servings:
  hosts:
  - :
```

And the config can not be unmarshaled by `gopkg.in/yaml.v2`

So add some parameter check, to avoid the problem

https://github.com/go-yaml/yaml/issues/780

### CODE REVIEW

**Comment by asdfsx** [comment]
@owlet42

**Comment by asdfsx** [comment]
any suggestions?

**Review by LaynePeng — APPROVED** [review]
LGTM

**Comment by asdfsx** [comment]
It seems merge is failed?

**Review by owlet42 — APPROVED** [review]

**Pull request merged**
