### PR TITLE
Make Kubefate support Fate v1.5.3

### LINKED ISSUE #555: Support FATE v1.5.3
**Summary**

Include docker-compose and Kubernetes

**User Story**

As an admin, I would like KubeFATE to support FATE v1.5.3

**Intake type**

Call

### PR DESCRIPTION
**Pull request by JingChen23**
# Description

Fixes #555

Changes:

1. Changed the version numbers everywhere to 1.5.3
2. Change the legacy ingress format, which has been abandoned by the latest K8s version.
3. Fix a python dependency issue, without the fix, the client image can not become running.
4. Support configure the username/password for login the fateboard UI.

# Test
## docker test

Step 1: `git clone git@github.com:FederatedAI/FATE.git` checkout branch v1.5.3, and build/load the docker images.
Step 2: `git clone  https://github.com/JingChen23/KubeFATE.git` which contains my change, and build/load the docker images.
Step 3: Modify the parties.conf file, change the ip addresses, then run generate_conf.sh
Step 4: Run docker_deploy.sh.
Step 5: Run test.sh, verified that the results are succeed:

```
*********************end docker log***************************
party 9999 cluster toy_example test is success!

[2022-03-17 04:47:31] Start task: ['python', '/data/projects/fate/examples/min_test_task/../../python/fate_flow/fate_flow_client.py', '-f', 'query_job', '-j', '202203170446099661160', '-r', 'guest']
[2022-03-17 04:47:32] Current task status: success
```

Screen Shot 2022-03-17 at 1 48 22 PM

## K8s test
Step 1: Install minikube on the vm.
Step 2: Makethe helm chart file and upload the helm chart.
Step 3: Modify the cluster.yaml config files, make it to be 2 parties.
Step 4: kubefate cluster install -f <the cluster files>

Verified that the clusters are running, all the pods are healthy.
Verified that the fateboard UI can be logged in, and the noteboard UI can be accessed.
Verified that jobs can be submitted to fate, and run successfully.

Screen Shot 2022-03-18 at 4 03 48 PM

### CODE REVIEW

**Review by LaynePeng — APPROVED** [review]
LGTM

**Comment by LaynePeng** [comment]
```
Change the legacy ingress format, which has been abandoned by the latest K8s version.
```

So, what is the latest downward compatible Kubernetes version?

**Comment by JingChen23** [comment]
> ```
> Change the legacy ingress format, which has been abandoned by the latest K8s version.
> ```
> 
> So, what is the latest downward compatible Kubernetes version?

The Kubernetes version must be >=1.19 now, before this change, the Kubernetes version must be <1.22, my thought is we should depend on the newer kubernetes.

**Review by owlet42 — APPROVED** [review]
LGTM

**Pull request merged**
